language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t pratish420/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pratish420/docker-react npm run test
